Repository codestates-seb/seb39_main_022, pull requests merged in 2022-09, with the labels that each got.

#28 [FE] Favorite Page
  client/data.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/component/Map.js
  client/src/component/Pagenation.js
  client/src/page/Detail.js
  client/src/page/Favorite.js
  client/src/page/Landing.js
Labels: dev-front

#33 Pageable Re
  server/wheelmaster/src/main/generated/main/wheelmaster/comment/mapper/CommentMapperImpl.java
  server/wheelmaster/src/main/generated/main/wheelmaster/member/mapper/MemberMapperImpl.java
  server/wheelmaster/src/main/generated/main/wheelmaster/vote/mapper/VoteMapperImpl.java
  server/wheelmaster/src/main/generated/main/wheelmaster/wheelcenter/mapper/WheelCenterMapperImpl.java
  server/wheelmaster/src/main/java/main/wheelmaster/comment/controller/CommentController.java
  server/wheelmaster/src/main/java/main/wheelmaster/comment/service/CommentService.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/WebConfigSupport.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/WebInterceptorConfig.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/argumentresolver/Login.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/argumentresolver/LoginMemberArgumentResolver.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/interceptor/LoginCheckInterceptor.java
  server/wheelmaster/src/main/java/main/wheelmaster/member/controller/MemberController.java
  server/wheelmaster/src/main/java/main/wheelmaster/member/service/MemberService.java
  server/wheelmaster/src/main/java/main/wheelmaster/swagger/SwaggerConfig.java
  server/wheelmaster/src/main/java/main/wheelmaster/vote/controller/VoteController.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/dto/WheelCenterResponseDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/mapper/WheelCenterMapper.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/repository/WheelCenterRepository.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/service/WheelCenterService.java
Labels: ToDo, dev-back

#31 Feature favorite
  server/wheelmaster/.gitignore
  server/wheelmaster/src/main/generated/main/wheelmaster/comment/mapper/CommentMapperImpl.java
  server/wheelmaster/src/main/generated/main/wheelmaster/member/mapper/MemberMapperImpl.java
  server/wheelmaster/src/main/generated/main/wheelmaster/vote/mapper/VoteMapperImpl.java
  server/wheelmaster/src/main/generated/main/wheelmaster/wheelcenter/mapper/WheelCenterMapperImpl.java
  server/wheelmaster/src/main/java/main/wheelmaster/exception/ExceptionCode.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/dto/request/FavoritePlacePostDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/dto/response/FavoritePlaceResponseDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/mapper/FavoritePlaceMapper.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/repository/FavoritePlaceRepository.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/service/FavoritePlaceService.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/WebConfig.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/argumentresolver/Login.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/argumentresolver/LoginMemberArgumentResolver.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/interceptor/LoginCheckInterceptor.java
  server/wheelmaster/src/main/java/main/wheelmaster/member/entity/Member.java
  server/wheelmaster/src/main/java/main/wheelmaster/vote/controller/VoteController.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/utils/WheelCenterUtils.java
  server/wheelmaster/src/main/resources/application.yml
Labels: dev-back

#32 Feature serch ldk
  server/wheelmaster/.gitignore
  server/wheelmaster/build.gradle
  server/wheelmaster/src/main/java/main/wheelmaster/comment/controller/CommentController.java
  server/wheelmaster/src/main/java/main/wheelmaster/comment/mapper/CommentMapper.java
  server/wheelmaster/src/main/java/main/wheelmaster/comment/service/CommentService.java
  server/wheelmaster/src/main/java/main/wheelmaster/exception/ExceptionCode.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/dto/request/FavoritePlacePostDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/mapper/FavoritePlaceMapper.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/repository/FavoritePlaceRepository.java
  server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/service/FavoritePlaceService.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/WebConfigSupport.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/argumentresolver/Login.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/argumentresolver/LoginMemberArgumentResolver.java
  server/wheelmaster/src/main/java/main/wheelmaster/global/interceptor/LoginCheckInterceptor.java
  server/wheelmaster/src/main/java/main/wheelmaster/member/controller/MemberController.java
  server/wheelmaster/src/main/java/main/wheelmaster/member/dto/MemberRequestDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/member/service/MemberService.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/InMemoryProviderRepository.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/JwtTokenProvider.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/LoginResponse.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/Oauth2Member.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/Oauth2MemberRepository.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthAdapter.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthAttributes.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthConfig.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthController.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthProperties.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthProvider.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthService.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/OauthTokenResponse.java
  server/wheelmaster/src/main/java/main/wheelmaster/oauth2/UserProfile.java
  server/wheelmaster/src/main/java/main/wheelmaster/swagger/SwaggerConfig.java
  server/wheelmaster/src/main/java/main/wheelmaster/token/dto/TokenRequestDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/token/dto/TokenResponseDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/token/entity/Token.java
  server/wheelmaster/src/main/java/main/wheelmaster/token/mapper/TokenMapper.java
  server/wheelmaster/src/main/java/main/wheelmaster/token/provider/JwtTokenProviderLocal.java
  server/wheelmaster/src/main/java/main/wheelmaster/token/repository/TokenRepository.java
  server/wheelmaster/src/main/java/main/wheelmaster/token/service/AuthService.java
  server/wheelmaster/src/main/java/main/wheelmaster/vote/controller/VoteController.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/InitController.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/dto/WheelCenterResponseDto.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/entity/WheelCenter.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/mapper/WheelCenterMapper.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/repository/WheelCenterRepository.java
  server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/service/WheelCenterService.java
  server/wheelmaster/src/main/resources/application-oauth.yml
  server/wheelmaster/src/main/resources/application.properties
  server/wheelmaster/src/main/resources/application.yml
  server/wheelmaster/src/main/resources/static/index.html
Labels: ToDo, dev-back
